linters-settings:
  funlen:
    lines: 120
    statements: 100
  gci:
    sections:
      - standard
      - default
  godox:
    keywords:
      - FIXME
      - BUG

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
issues:
  exclude-dirs:
    - scripts
    - vendor
    - ci
  exclude-rules:
    - linters:
        - dupl
      path: application\.go
