before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/panurge
    goos:
      - linux
      - windows
      - darwin
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: navigacontentlab
    name: panurge
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - tap:
      owner: Infomaker
      name: homebrew-core
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/navigacontentlab/panurge
    description: Panurge utility
    url_template: "https://github.com/navigacontentlab/panurge/releases/{{ .Tag }}/{{ .ArtifactName }}"
release:
  disable: true
