// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testservice/service.proto

package testservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ThingReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingReq) Reset()         { *m = ThingReq{} }
func (m *ThingReq) String() string { return proto.CompactTextString(m) }
func (*ThingReq) ProtoMessage()    {}
func (*ThingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cdcdba669592600, []int{0}
}

func (m *ThingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingReq.Unmarshal(m, b)
}
func (m *ThingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingReq.Marshal(b, m, deterministic)
}
func (m *ThingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingReq.Merge(m, src)
}
func (m *ThingReq) XXX_Size() int {
	return xxx_messageInfo_ThingReq.Size(m)
}
func (m *ThingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingReq.DiscardUnknown(m)
}

var xxx_messageInfo_ThingReq proto.InternalMessageInfo

func (m *ThingReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ThingRes struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThingRes) Reset()         { *m = ThingRes{} }
func (m *ThingRes) String() string { return proto.CompactTextString(m) }
func (*ThingRes) ProtoMessage()    {}
func (*ThingRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_0cdcdba669592600, []int{1}
}

func (m *ThingRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThingRes.Unmarshal(m, b)
}
func (m *ThingRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThingRes.Marshal(b, m, deterministic)
}
func (m *ThingRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThingRes.Merge(m, src)
}
func (m *ThingRes) XXX_Size() int {
	return xxx_messageInfo_ThingRes.Size(m)
}
func (m *ThingRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ThingRes.DiscardUnknown(m)
}

var xxx_messageInfo_ThingRes proto.InternalMessageInfo

func (m *ThingRes) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*ThingReq)(nil), "testservice.ThingReq")
	proto.RegisterType((*ThingRes)(nil), "testservice.ThingRes")
}

func init() {
	proto.RegisterFile("testservice/service.proto", fileDescriptor_0cdcdba669592600)
}

var fileDescriptor_0cdcdba669592600 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x49, 0x2d, 0x2e,
	0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0xdc, 0x48, 0x52, 0x4a, 0x72, 0x5c, 0x1c, 0x21, 0x19, 0x99, 0x79, 0xe9, 0x41, 0xa9, 0x85,
	0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60,
	0xb6, 0x92, 0x1a, 0x5c, 0xbe, 0x58, 0x48, 0x8a, 0x8b, 0xa3, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf,
	0x18, 0xa6, 0x06, 0xce, 0x37, 0xb2, 0xe7, 0x62, 0x09, 0x49, 0x2d, 0x2e, 0x11, 0x32, 0xe7, 0x62,
	0x77, 0xc9, 0x07, 0xeb, 0x10, 0x12, 0xd5, 0x43, 0xb2, 0x48, 0x0f, 0x66, 0x8b, 0x14, 0x56, 0xe1,
	0x62, 0x27, 0xde, 0x28, 0x64, 0x77, 0x25, 0xb1, 0x81, 0xdd, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xc4, 0xce, 0x6c, 0x7c, 0xc8, 0x00, 0x00, 0x00,
}
